INSERT INTO users (username, password) VALUES
('jon', 'password'),
('joy', 'password');

INSERT INTO characters (name, art, home_thumbnail, home_sprite, battle_thumbnail, spritesheet, reverse_spritesheet, health, attack, description, subtitle) VALUES
('Herja', '/herja/herja-art.png', '/herja/herja-home.jpg', '/herja/herja-home-sprite.png', '/herja/herja-battle.jpg', '/herja/herja-spritesheet.png', '/herja/herja-reverse-spritesheet.png', 100, 20, 'This agent captain appears as stark and cold as the blade she wields, but underneath that gruff exterior she''s just as emotional as anyone else. Whenever she finds herself falling in love, she throws herself into her training, hammering it out with every blow of her sword.', 'Lady Mercenary'),
('Lamretta', '/lamretta/lamretta-art.png', '/lamretta/lamretta-home.jpg', '/lamretta/lamretta-home-sprite.png', '/lamretta/lamretta-battle.jpg', '/lamretta/lamretta-spritesheet.png', '/lamretta/lamretta-reverse-spritesheet.png', 100, 25, 'Lamretta''s favorite form of charity is passing around a bottle. For her there''s no better way to connect with others than through the sweet, sweet taste of wine.', 'Heavy Drinking Nun'),
('Seofon', '/seofon/seofon-art.png', '/seofon/seofon-home.jpg', '/seofon/seofon-home-sprite.png', '/seofon/seofon-battle.jpg', '/seofon/seofon-spritesheet.png', '/seofon/seofon-reverse-spritesheet.png', 110, 35, 'The Eternals are a powerful group that rule the far reaches of the sky, and are seen as a threat to the entire skydom. Seofon seems rather carefree for the leader of the Eternals, but he''s actually a proud and driven man. The fearsome powers he commands could shake the very heavens, but he wields them only to right the world''s wrongs. He''s also frighteningly fond of swords.', 'The Eternals'),
('Sarasa', '/sarasa/sarasa-art.png', '/sarasa/sarasa-home.jpg', '/sarasa/sarasa-home-sprite.png', '/sarasa/sarasa-battle.jpg', '/sarasa/sarasa-spritesheet.png', '/sarasa/sarasa-reverse-spritesheet.png', 110, 35, 'The Eternals are a powerful group that rule the far reaches of the sky, and are seen as a threat to the entire skydom. This fierce warrior understands the laws of nature far better than any other, and survival of the fittest has become her creed. She fights tooth and claw to remain at the top of the food chain, so that she''ll never have to lose anything again.', 'The Eternals'),
('Hallessena', '/hallessena/hallessena-art.png', '/hallessena/hallessena-home.jpg', '/hallessena/hallessena-home-sprite.png', '/hallessena/hallessena-battle.jpg', '/hallessena/hallessena-spritesheet.png', '/hallessena/hallessena-reverse-spritesheet.png', 110, 35, 'After spending most of her childhood being picked on, this little lady''s finally decided to turn the tables. Although she desires ease and peace of mind for all deep down, her abrasiveness has earned her the nickname "The Walking Wraith."', 'Destruction Catastrophe');